name: Cypress Tests

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          quiet: true
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
      - name: Upload screenshots
        uses: actions/upload-artifact@v5.0.0
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
